### ISSUE TITLE
Plugin Review

### ISSUE THREAD

**Issue by agung2001** [agungnugroho24/techtest_artistudio#1]
Hi @agungnugroho24 🖐️😁
firstly I wanted to say thank you 
for taking the time to do the test

but I think you might miss understand the test
you might want to read the test again [WordPress Developer (Senior)](https://brain.artistudio.xyz/knowledge/technical/job-vacancy/test/wordpress-developer-senior-.md)
The end results what we're expecting is something like : 
- [artistudioxyz/floating-awesome-button](https://github.com/artistudioxyz/floating-awesome-button)
- [agung2001/calo](https://github.com/agung2001/wp-calo)

where the repository will contains the custom plugin only, not the whole WordPress installation
also, you have missed some of the important aspect of the test like : 
1. You're using plugin Popup Maker and WPCode instead of creating a custom plugin from scratch using [Dot Framework](https://github.com/artistudioxyz/dot-framework)
2. `Docs.md` should explain a custom feature that you've built with DOT Framework and the corresponding concept comes with it such as CPT, Custom Field, namespace, singleton pattern, and prototype pattern inside of your plugin.

The essence of this test is to showcase your capability, when it comes to creating a custom WordPress plugin without a help of any other plugin. This is required, because most of our projects is to deal with a custom plugin

If you wish to continue, you can fix this repository, then comment on this issue when you feel comfortable, for the repository to be reviewed again

thx 😁👍

**Comment by agungnugroho24** [comment]
Thank you for the correction, i will fix it as soon as possible

Pada tanggal Sel, 19 Sep 2023 pukul 08.07 Agung Sundoro <
***@***.***> menulis:

**Comment by agungnugroho24** [comment]
Hi Agung Sundoro ***@***.***)

I have already fix it and now you can check the code, thank you for your
attention

Pada Sel, 19 Sep 2023 pukul 12.27 Dev ***@***.***> menulis:

**Comment by agung2001** [comment]
hi @agungnugroho24 , 

thx for resubmitting, but you might want to read my previous comment.
it seems that you still don't understand the test.
you must implement the popup plugin using Dot Framework

**Comment by agungnugroho24** [comment]
I've already used dot framework on last source code, is that still wrong?
Maybe you can give an example what is like using dot framework for
wordpress plugin so i can figure it out, thanks

**Comment by agung2001** [comment]
hi @agungnugroho24 

ow yeah sure 

for the tutorial you can watch this playlist on YouTube :  
https://www.youtube.com/watch?v=xbTiYXXkF-w&list=PLc4H2My9zgNWAVFQiK3nRpnSOLByUh8Wn
that'll explain our expected outcome of the test

the repository that we're expecting is something like this : 
https://github.com/agung2001/wp-nongol/tree/episode-2

**Comment by agungnugroho24** [comment]
Hi, i have a question the DOT Framework is Development Oriented
Triangulation (DOT) framework or .NET Framework?

Pada Rab, 18 Okt 2023 pukul 14.02 Agung Sundoro ***@***.***>
menulis:

**Comment by agung2001** [comment]
hi @agungnugroho24 

no man, [DOT Framework](https://github.com/artistudioxyz/dot-framework) is a custom framework developed by artistudio team to create custom WordPress plugin.

**Comment by agungnugroho24** [comment]
Is this https://github.com/agung2001/wp-nongol/tree/episode-2 the DOT
Framework <https://github.com/artistudioxyz/dot-framework> that artistudio
team developed? Or which one is custom framework that artistudio
team create?
so i can develop from your custom framework

Pada Rab, 18 Okt 2023 pukul 15.19 Agung Sundoro ***@***.***>
menulis:

**Comment by agung2001** [comment]
yup exactly that's the framework
you can start whatever you're comfortable with : 
- https://github.com/artistudioxyz/dot-framework : from scratch or
- https://github.com/agung2001/wp-nongol/tree/episode-2 : continue from this repository

**Comment by agungnugroho24** [comment]
Okay, i will custom one of them. Thank you then.

Pada Rab, 18 Okt 2023 pukul 15.46 Agung Sundoro ***@***.***>
menulis:

**Comment by agung2001** [comment]
close the issue been stale for long time
